# Generated by Django 5.1.5 on 2025-02-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_user_access_token_user_access_token_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='employee_us_email_b9ea0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='employee_us_mobile_67bf35_idx',
        ),
    ]
