# Generated by Django 5.1.5 on 2025-03-12 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_user_employee_us_email_b9ea0a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('mobile', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email', 'mobile'), name='worker')],
            },
        ),
    ]
