# Generated by Django 5.1.5 on 2025-03-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
