# Generated by Django 5.1.5 on 2025-02-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permission_key',
            field=models.CharField(default='default_key', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permissions', models.ManyToManyField(to='employee.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.role')),
            ],
        ),
    ]
