# Generated by Django 5.1.5 on 2025-02-11 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_permission_permission_key_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permissions',
            field=models.ManyToManyField(related_name='user_permissions', to='employee.permission'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
