# Generated by Django 5.1.5 on 2025-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_userpermission_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdepartment',
            name='unique_user_department',
        ),
        migrations.RemoveConstraint(
            model_name='userdesignation',
            name='unique_user_designation',
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role',
        ),
        migrations.AddConstraint(
            model_name='userdepartment',
            constraint=models.UniqueConstraint(fields=('user', 'department'), name='user_department'),
        ),
        migrations.AddConstraint(
            model_name='userdesignation',
            constraint=models.UniqueConstraint(fields=('user', 'designation'), name='user_designation'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='user_role'),
        ),
    ]
