# Generated by Django 5.1.5 on 2025-02-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_userdepartment_unique_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permissions',
            field=models.ManyToManyField(related_name='role_permissions', to='employee.permission'),
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
