# Generated by Django 5.1.5 on 2025-02-18 11:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnstile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnstileLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code_scan', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied')], max_length=50)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('turnstile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnstile_logs', to='visitor.turnstile')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254, unique=True)),
                ('visitor_mobile', models.CharField(max_length=15, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('visit_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_roles', to='employee.role')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='turnstile',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnstile_entries', to='visitor.visitor'),
        ),
    ]
