# Generated by Django 5.1.5 on 2025-02-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_permission_permission_key_rolepermission'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_roles', to='employee.role'),
        ),
    ]
