# Generated by Django 5.1.5 on 2025-03-19 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDetails',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254, unique=True)),
                ('visitor_mobile', models.CharField(max_length=15, unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='turnstilelog',
            name='turnstile',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='assigned_role',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='registered_by',
        ),
        migrations.CreateModel(
            name='VisitorDocuments',
            fields=[
                ('visitor_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_document_name', models.CharField(max_length=100)),
                ('visitor_document_photo', models.ImageField(upload_to='visitor_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visitor.visitordetails')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorPerson',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=100)),
                ('person_department', models.CharField(max_length=255)),
                ('meeting_purpose', models.CharField(max_length=512)),
                ('meeting_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitor.visitordetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Turnstile',
        ),
        migrations.DeleteModel(
            name='TurnstileLog',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
